[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

; SPIFFS filesystem for AWS IoT certificates
board_build.filesystem = spiffs
board_build.partitions = min_spiffs.csv

lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson@6.21.3
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    
; PubSubClient default buffer (128 bytes) is too small for AWS IoT certs/payloads
build_flags =
    -DMQTT_MAX_PACKET_SIZE=2048
